{
 "title": "ShoeHub Business",
 "description": "All Business charts / analytics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "label_values(shoehub_payments{PaymentMethod=\"Card\"}, CountryCode)"
    }
   },
   {
    "name": "paymentMethod",
    "label": "Payment Method",
    "query": {
     "query": "label_values(shoehub_payments{CountryCode=\"US\"}, PaymentMethod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Business Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Card Payments by $paymentMethod",
   "type": "gauge",
   "description": "Shows Average Payment across methods of payment",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "shoehub_payments{CountryCode=\"US\"}",
     "legendFormat": "{{PaymentMethod}}"
    }
   ]
  },
  {
   "title": "Sales Today vs Sales Last Week",
   "type": "timeseries",
   "description": "Compare sales today with sales last week",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[$__interval])",
     "legendFormat": "Loafers Daily"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[$__interval] offset 1m) ",
     "legendFormat": "Loafers last week"
    }
   ]
  },
  {
   "title": " $paymentMethod payment amount accross countries",
   "type": "timeseries",
   "description": "Shows payment methods across countries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "repeat": "paymentMethod",
   "targets": [
    {
     "expr": "rate(shoehub_payments{PaymentMethod=\"$paymentMethod\"}[1m])",
     "legendFormat": "{{CountryCode}}"
    }
   ]
  },
  {
   "title": "Card Payment In Countries",
   "type": "piechart",
   "description": "Share of card payments by country",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(shoehub_payments{CountryCode=\"AU\", PaymentMethod=\"Card\"}[$__rate_interval])",
     "legendFormat": "Australia"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"IN\", PaymentMethod=\"Card\"}[$__rate_interval])",
     "legendFormat": "India"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"US\", PaymentMethod=\"Card\"}[$__rate_interval])",
     "legendFormat": "United States"
    }
   ]
  },
  {
   "title": "Cash Payments in Countries",
   "type": "piechart",
   "description": "Share of cash payments per country",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(shoehub_payments{CountryCode=\"US\", PaymentMethod=\"Cash\"}[$__rate_interval])",
     "legendFormat": "United States"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"IN\", PaymentMethod=\"Cash\"}[$__rate_interval])",
     "legendFormat": "India"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"AU\", PaymentMethod=\"Cash\"}[$__rate_interval])",
     "legendFormat": "Australia"
    }
   ]
  },
  {
   "title": "US - Daily Total Earnings ",
   "type": "timeseries",
   "description": "US Total Earnings per Day",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(shoehub_payments{CountryCode=\"US\", PaymentMethod=~\"Cash|Paypal|Card\"}[1d]))",
     "legendFormat": "Total Earnings"
    }
   ]
  },
  {
   "title": "US - Daily Earnings Comparison",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(shoehub_payments{CountryCode=\"US\", PaymentMethod=\"Card\"}[1d])",
     "legendFormat": "Card"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"US\", PaymentMethod=\"Paypal\"}[1d])",
     "legendFormat": "PayPal"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"US\", PaymentMethod=\"Cash\"}[1d])",
     "legendFormat": "Cash"
    }
   ]
  },
  {
   "title": "Total Shoe Sales",
   "type": "timeseries",
   "description": "Shows the total shoe sales over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(shoehub_sales{ShoeType=~\"Loafers|Boots|HighHeels\"}[1m]))",
     "legendFormat": "All shoe types"
    }
   ]
  },
  {
   "title": "Shoe Sales Comparison",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[1m])",
     "legendFormat": "Loafers"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"HighHeels\"}[1m])",
     "legendFormat": "High Heels"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Boots\"}[1m])",
     "legendFormat": "Boots"
    }
   ]
  },
  {
   "title": "Percentage of Payment Methods in $country",
   "type": "timeseries",
   "description": "Shows percentage of payment method in the US",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
   "repeat": "country",
   "targets": [
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Card\"})/ sum(shoehub_payments{CountryCode=\"$country\"}) * 100",
     "legendFormat": "Card"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Cash\"})/ sum(shoehub_payments{CountryCode=\"$country\"}) * 100",
     "legendFormat": "Cash"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Paypal\"})/ sum(shoehub_payments{CountryCode=\"$country\"}) * 100",
     "legendFormat": "Paypal"
    }
   ]
  }
 ]
}