{
 "title": "ShoeHub Business Charts",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "country",
    "label": "Country",
    "query": {
     "query": "label_values(shoehub_payments{PaymentMethod=\"Card\"}, CountryCode)"
    }
   },
   {
    "name": "paymentMethod",
    "label": "PaymentMethod",
    "query": {
     "query": "label_values(shoehub_payments{CountryCode=\"IN\"}, PaymentMethod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Business Charts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Card Payments by Country",
   "type": "piechart",
   "description": "Share of card payments by country",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(shoehub_payments{CountryCode=\"AU\",PaymentMethod=\"Card\"}[$__rate_interval])",
     "legendFormat": "Australia"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"IN\",PaymentMethod=\"Card\"}[$__rate_interval])",
     "legendFormat": "India"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"US\",PaymentMethod=\"Card\"}[$__rate_interval])",
     "legendFormat": "United States"
    }
   ]
  },
  {
   "title": "Card Payments in US",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "shoehub_payments{CountryCode=\"US\"}",
     "legendFormat": "{{PaymentMethod}}"
    }
   ]
  },
  {
   "title": "Payment amount by method of $paymentMethod",
   "type": "timeseries",
   "description": "View all payments by payment method across countries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "repeat": "paymentMethod",
   "targets": [
    {
     "expr": "shoehub_payments{PaymentMethod=\"$paymentMethod\"}",
     "legendFormat": "{{CountryCode}}"
    }
   ]
  },
  {
   "title": "Sale Today vs Sale Last Week",
   "type": "timeseries",
   "description": "Compare today's sale with last week",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[$__interval])",
     "legendFormat": "Current Loafers Sale"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[$__interval] offset 5m)",
     "legendFormat": "Loafers Sales 5m ago"
    }
   ]
  },
  {
   "title": "Daily US Sales",
   "type": "timeseries",
   "description": "US Daily Sales Insight",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(shoehub_payments{CountryCode=\"US\", PaymentMethod=\"Card\"}[1d])",
     "legendFormat": "Card"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"US\", PaymentMethod=\"Paypal\"}[1d])",
     "legendFormat": "Paypal"
    },
    {
     "expr": "rate(shoehub_payments{CountryCode=\"US\", PaymentMethod=\"Cash\"}[1d])",
     "legendFormat": "Cash"
    },
    {
     "expr": "sum(rate(shoehub_payments{CountryCode=\"US\", PaymentMethod=~\"Cash|Card|Paypal\"}[1d]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Percentage of Payment Methods in $country",
   "type": "timeseries",
   "description": "If payments by Paypal remain at 5% over time. We need to take action",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "repeat": "country",
   "targets": [
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Card\"}) / sum(shoehub_payments{CountryCode=\"$country\"}) * 100",
     "legendFormat": "Card"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Cash\"}) / sum(shoehub_payments{CountryCode=\"$country\"}) * 100",
     "legendFormat": "Cash"
    },
    {
     "expr": "sum(shoehub_payments{CountryCode=\"$country\", PaymentMethod=\"Paypal\"}) / sum(shoehub_payments{CountryCode=\"$country\"}) * 100",
     "legendFormat": "Paypal"
    }
   ]
  },
  {
   "title": "Sales",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Boots\"}[$__rate_interval])",
     "legendFormat": "Boots"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"HighHeels\"}[$__rate_interval])",
     "legendFormat": "HighHeels"
    },
    {
     "expr": "rate(shoehub_sales{ShoeType=\"Loafers\"}[$__rate_interval])",
     "legendFormat": "Loafers"
    }
   ]
  }
 ]
}